version: '3'
networks:
  unbound:
services:
  ukc-ep:
    image: "unboundtech/ukc-server:${UKC_VERSION:-latest}.vhsm"
    container_name: ukc-ep
    restart: always
    ports:
      - "443:8443"
      - "9021:9001"
      - "9022:9002"
      - "8082:8080"
    entrypoint: ["/unbound/start_ukc.sh", "ep", "ukc-partner", "ukc-aux"]
    hostname: ukc-ep
    env_file:
      settings.env
    networks:
      - unbound
  ukc-partner:
    image: "unboundtech/ukc-server:${UKC_VERSION:-latest}.vhsm"
    container_name: ukc-partner
    restart: always
    entrypoint: ["/unbound/start_ukc.sh", "partner", "ukc-ep", "ukc-aux"]
    hostname: ukc-partner
    depends_on:
      - "ukc-ep"
    ports:
      - "9023:9002"
    networks:
      - unbound
  ukc-aux:
    image: "unboundtech/ukc-server:${UKC_VERSION:-latest}.vhsm"
    container_name: ukc-aux
    restart: always
    entrypoint: ["/unbound/start_ukc.sh", "aux", "ukc-ep", "ukc-partner"]
    hostname: ukc-aux
    depends_on:
      - "ukc-ep"
      - "ukc-partner"
    ports:
      - "9024:9001"
    networks:
      - unbound
  ukc-client:
    image: "unboundtech/ukc-client:${UKC_VERSION:-latest}.vhsm.dev"
    container_name: ukc-client
    restart: always
    hostname: ukc-client
    depends_on:
      - "ukc-ep"
    ports:
      - "8081:8081"
      - "8444:8443"
    env_file:
      settings.env
    networks:
      - unbound
