version: '3'
services:
  ukc-ep:
    image: "local/ukc"
    container_name: ukc-ep
    restart: always
    ports:
     - "8443:8443"
    command: ["ep", "ukc-partner", "ukc-aux"] 
    hostname: ukc-ep
    environment:
      UKC_NOCERT: 'true'
      UKC_PASSWORD: 'Unbound1!'
      UKC_PARTITION: 'test'
      UKC_CERTIFICATE_HOST_NAME: 'localhost'
  ukc-partner:
    image: "local/ukc"
    container_name: ukc-partner
    restart: always
    command: ["partner", "ukc-ep", "ukc-aux"]
    hostname: ukc-partner
    depends_on:
      - "ukc-ep"
  ukc-aux:
    image: "local/ukc"
    container_name: ukc-aux
    restart: always
    command: ["aux", "ukc-ep", "ukc-partner"]
    hostname: ukc-aux
    depends_on:
      - "ukc-ep"
      - "ukc-partner"
